# server
server:
  port: 8090
  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://61.34.174.13:33306/test_ih?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: next1212
